FROM rust:alpine

COPY --from=golang:1.17-alpine /usr/local/go/ /usr/local/go/

ENV PATH="/usr/local/go/bin:${PATH}"

RUN apk add --no-cache git make musl-dev perl linux-headers protoc

RUN rustup toolchain install stable -t x86_64-unknown-linux-musl

ENV RUSTFLAGS="-C target-feature=-crt-static"

ENTRYPOINT ["/bin/ash"]